version: '3.4'
services:
  api1: &api
    build:
      dockerfile: ./Dockerfile
      context: .
    image: luizimcpi/rinha-2024q1-crebito
    restart: always
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    networks: 
      - prod
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '30MB'
  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks: 
      - prod
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50MB'

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    networks:
      - prod
    environment:
      POSTGRES_DB: rinhabank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - ./sql/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '440MB'

networks:
  prod:
    driver: bridge