### Variaveis
@apiurl = http://localhost:8080

### POST criar transacao
POST {{apiurl}}/clientes/1/transacoes HTTP/1.1
Content-Type: application/json

{
    "valor": 1000,
    "tipo" : "d",
    "descricao" : "abcdefghijk"
}